filebeat.prospectors:
- input_type: log
  paths:
    - /logs/postgres-sonar/*.log
    - /logs/sonarqube/*.log
    - /logs/jenkins/*.log
#output.elasticsearch:
#  hosts: ["${ELASTICSEARCH_HOST}"]
output.logstash:
  hosts: ["${LOGSTASH_HOST}"]

