# Created by Wolfgang Grossinger
FROM sonarqube:latest
MAINTAINER Wolfgang Grossinger <wolfgang.grossinger@gmail.com>
ENV SONARQUBE_JDBC_USERNAME=sonar
ENV SONARQUBE_JDBC_PASSWORD=sonar
ENV SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar
